language: java
jdk:
 - oraclejdk8


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-east-2"
  app: "n9cttxxx8p"
  env: "Default-Environment"
  bucket_name: "elasticbeanstalk-us-east-2-523799450750"
  on:
    branch: master