server:
  port: 8080
  context-path: /curriculum

spring:
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true

#liquibase:
#  change-log: classpath:/db/changelog-master.xml

logging:
  level:
    org.hibernate.tool.hbm2ddl: debug
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.web: trace

liquibase:
  change-log: classpath:/db/changelog-master.xml