package ru.curriculum.domain.etp.repository;

import org.springframework.data.repository.PagingAndSortingRepository;
import ru.curriculum.domain.etp.entity.organizationallyMethodicalSection.OrganizationallyMethodicalSectionInfo;

public interface OrganizationallyMethodicalSectionInfoRepository extends PagingAndSortingRepository<OrganizationallyMethodicalSectionInfo, Integer> {
}
